name: mertgul
description: My personal website

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  coolors_palette: ^0.0.2
  flutter_icons: ^1.1.0
  http: ^0.12.2
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  assets:
    - images/background.png
    - images/profile.jpg
  fonts:
    - family: RobotoCondensed
      fonts:
        - asset: fonts/RobotoCondensed-Bold.ttf
        - asset: fonts/RobotoCondensed-BoldItalic.ttf
        - asset: fonts/RobotoCondensed-Italic.ttf
        - asset: fonts/RobotoCondensed-Light.ttf
        - asset: fonts/RobotoCondensed-LightItalic.ttf
        - asset: fonts/RobotoCondensed-Regular.ttf
    - family: Oswald
      fonts:
        - asset: fonts/Oswald-VariableFont_wght.ttf
